INSERT INTO fabricante(id, nombre) VALUES(1, 'Apple');
INSERT INTO fabricante(id, nombre) VALUES(2, 'Motorola');
INSERT INTO fabricante(id, nombre) VALUES(3, 'Samsung');
INSERT INTO fabricante(id, nombre) VALUES(4, 'Nokia');
INSERT INTO fabricante(id, nombre) VALUES(5, 'Tecno Mobile');
INSERT INTO fabricante(id, nombre) VALUES(6, 'Huawei');
INSERT INTO fabricante(id, nombre) VALUES(7, 'Oppo');
INSERT INTO fabricante(id, nombre) VALUES(8, 'Honor');
INSERT INTO fabricante(id, nombre) VALUES(9, 'Xiaomi');

INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(1, 'Tecno Spark 10PRO', 215.24, 5);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(2, 'Honor Magic 5 Lite ', 373.55, 8);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(3, 'Audifonos Nokia In Ear Comfort Earbuds', 49.75, 4);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(4, 'Oppo A77', 298.62, 7);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(5, 'Huawei Nova 11i', 300.63, 6);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(6, 'Apple Watch Ultra', 1087.32, 1);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(7, 'iPhone 14PRO ', 1380.99, 1);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(8, 'Xiami Redmi Note 12',219.2, 9);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(9, 'Audifonos Motorola IN Ear Buds 085', 52.24, 2);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(10, 'Samsung Galaxy ZFLIP5', 1493.23, 3);
INSERT INTO producto(id, nombre, precio, id_fabricante) VALUES(11, 'Tablet Samsung 12.4" S9PLUS', 1367, 3);